# Optional github repository url, used mainly to generate changelog links
github = "https://github.com/oknozor/cocogitto"

# Optional contributor list
# intended to map git signature to github username
# and generate changelog links to their github profiles
authors = [
    { signature = "Paul Delafosse", username = "oknozor" },
    { signature = "Jack Dorland", username = "jackdorland" },
    { signature = "Mike Lubinets", username = "mersinvald" },
    { signature = "Marcin Puc", username = "tranzystorek-io" },
    { signature = "Renault Fernandes", username = "renaultfernandes" },
    { signature = "Pieter Joost van de Sande", username = "pjvds" },
    { signature = "orhun", username = "orhun" },
    { signature = "Danny Tatom", username = "its-danny" },
    { signature = "Clément Poissonnier", username = "cpoissonnier" },
]


# Optional changelog path ("CHANGELOG.md" if omitted)
changelog_path = "CHANGELOG.md"

# A list of command to run BEFORE creating a version.
# All change generated by those commands will be committed with the generated version commit.
# `{{version}}` will be interpretted as your target version
pre_bump_hooks = [
    "sh -c \"./ci/check_branch.sh\"",
    "cargo test -- --test-threads 1",
    "cargo clippy",
    "cargo build --release",
    "cargo fmt --all",
    "cargo bump {{version}}",
]

# A list of command to run AFTER creating a version.
# `{{version}}` will be interpretted as your target version
post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
    "cargo package",
    "cargo publish"
]

# A custom named bump profile, the inner post/pre bump hook will be used
# instead of the main ones when running `cog bump --hook-profile example --auto`
[bump_profiles.example]
pre_bump_hooks = [
    "echo 'bumping from {{latest}} to {{version}} using a named profile'"
]
post_bump_hooks = [
    "echo 'we are done'"
]

# An optional list of additional allowed commit type
# `coco {commit_type}` commit command will be generated at runtime
[commit_types]
ex = { changelog_title = "This is the markdown title for `ex` commit type" }
