name: Deploy GitHub Pages

on:
  workflow_dispatch:
    inputs:
      deploy_pages:
        description: "Deploy GitHub Pages manually"
        required: false
        type: boolean
        default: true
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_pages:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy_pages || github.event_name == 'workflow_run' && github.event.workflow_conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: website/package-lock.json
          node-version: 20
          cache: npm

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci
        working-directory: ./website

      - name: Build with VitePress
        run: npm run docs:build
        working-directory: ./website

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/.vitepress/dist

  deploy_pages:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build_pages
    runs-on: ubuntu-latest
    name: Deploy GitHub Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4